[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/mhils/internet-packet.git"]
git = "https://github.com/mhils/internet-packet.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
