[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/cloudflare/boringtun?rev=2f3c85f5c4a601018c10b464b1ca890d9504bf6e"]
git = "https://github.com/cloudflare/boringtun"
rev = "2f3c85f5c4a601018c10b464b1ca890d9504bf6e"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
