[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/cloudflare/boringtun?rev=e3252d9c4f4c8fc628995330f45369effd4660a1"]
git = "https://github.com/cloudflare/boringtun"
rev = "e3252d9c4f4c8fc628995330f45369effd4660a1"
replace-with = "vendored-sources"

[source."git+https://github.com/smoltcp-rs/smoltcp?rev=ef67e7b46cabf49783053cbf68d8671ed97ff8d4"]
git = "https://github.com/smoltcp-rs/smoltcp"
rev = "ef67e7b46cabf49783053cbf68d8671ed97ff8d4"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
