[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/emanuele-em/apple-security?rev=eb6abf2dabe3881620436eba952750600bef267b"]
git = "https://github.com/emanuele-em/apple-security"
rev = "eb6abf2dabe3881620436eba952750600bef267b"
replace-with = "vendored-sources"

[source."git+https://github.com/mhils/internet-packet.git"]
git = "https://github.com/mhils/internet-packet.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
